
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 33
#define YY_END_OF_BUFFER 34
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[284] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   34,   32,   32,   32,
       32,   32,   33,    2,   33,    4,    5,   33,   17,   33,
       33,   32,   32,   32,   32,   32,   32,   32,   33,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   33,   32,
       32,    0,    0,    0,    0,    0,    0,    4,    9,   17,
       16,   17,    0,    0,   12,   14,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   10,   29,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       23,    0,   21,    0,    0,    0,   20,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   29,    0,
        0,   30,    0,   26,    0,    0,    0,   29,   19,    0,
        0,    0,    0,    0,    0,   31,    0,   18,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   19,
        0,    0,    0,    0,    3,    0,   18,    0,    0,    0,
        0,    0,    0,    0,    0,   28,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   25,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   25,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   27,   24,    0,    0,
        0,    0,    1,    0,    0,    0,    0,    0,    1,    0,
        0,    1,    0,    7,    0,    8,    0,    0,    0,    0,
        1,    0,    0,    8,    0,    0,    0,    0,   15,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   13,    0,
        0,    0,    0,    0,   13,   11,   22,    0,   11,   22,
        0,    6,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    4,    1,    5,
        6,    1,    1,    7,    8,    1,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   10,   11,    1,
       12,   13,    1,    1,   14,   15,   15,   15,   15,   16,
       17,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
        1,    1,    1,    1,   18,    1,   19,   20,   21,   21,

       22,   23,   21,   24,   25,   21,   21,   26,   27,   28,
       29,   30,   21,   31,   32,   33,   34,   35,   21,   21,
       36,   21,   37,   38,   39,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[40] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    5,    6,    1,
        7,    1,    1,    8,    8,    8,    8,    9,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,    1,    1,   11
    } ;

static const flex_int16_t yy_base[302] =
    {   0,
        0,    2,   37,    0,  847,  845,   76,  115,  807,  805,
      154,    0,  185,    0,  803,  801,  221,    0,    0,    0,
      833,  831,    0,    0,  794,  792,  260,    0,    0,    0,
      824,  822,    0,    0,  298,  299,  300,  307,  344,    0,
        0,    0,    0,    4,  382,    0,  822,   20,   21,  855,
       22,   83,  855,  855,  810,    0,  855,    0,   27,   88,
        0,  785,  813,   25,   98,  302,  101,   89,    0,   99,
      811,   92,  108,    6,  803,  806,  805,   96,   93,  128,
      130,  133,  134,  135,  138,  312,  793,    0,    0,  800,
      855,  140,  304,  305,  855,    0,  764,  785,  193,  782,

      194,  321,  322,  323,  339,    0,  855,  759,  782,  786,
      778,  319,  337,  301,  771,  420,  764,  347,  342,  353,
      855,  360,  855,  364,  758,  366,  855,  422,  421,  756,
      748,  743,  195,  425,  439,  440,  442,  734,  737,    4,
      426,  855,  747,  855,  472,    0,  488,  735,  731,  443,
      452,  453,  459,  109,  690,  855,  303,  684,  463,  468,
      483,  464,  653,  681,  350,  424,  680,  371,  679,  678,
      490,  491,  496,  438,  855,  657,  675,  505,  509,  507,
      512,  643,  531,  131,  510,  855,  552,  454,  529,  526,
      643,  521,  642,  533,  536,  655,  855,    0,    0,  568,

      670,   90,  352,  532,  547,  553,  669,  556,  635,  570,
      571,  635,  663,  578,  653,  466,  549,  584,  588,  589,
      653,  593,  629,  593,  594,  577,  855,  855,  590,  608,
      595,  602,  606,  571,  609,  566,  527,  517,  612,  510,
      613,  616,  620,  624,  522,  520,  499,  500,  476,  625,
      493,  626,  443,  455,  420,  397,  396,  627,  855,  629,
      359,  350,  630,  636,  355,  639,  640,  641,  338,  642,
      193,  643,  189,  645,  196,   94,   24,  656,    9,    5,
      659,  660,  855,  687,  698,  709,  720,  726,  736,  745,
      755,  764,  774,  783,  792,  799,  808,  817,  826,  835,

      844
    } ;

static const flex_int16_t yy_def[302] =
    {   0,
      284,  284,  283,    3,  285,  285,  286,  286,  285,  285,
      283,   11,  285,   13,  285,  285,  283,   17,    3,    3,
      285,  285,    8,    8,  285,  285,  283,   27,    3,    3,
      285,  285,    8,    8,   27,   27,   27,   27,   27,   39,
       39,   39,  285,  285,  283,   45,  283,  287,  287,  283,
      287,  287,  283,  283,  283,  288,  283,  289,  283,  290,
      291,  283,  283,  292,  292,  292,  292,  292,  293,  283,
      294,  294,  294,  294,  283,  283,  283,  294,  295,  283,
      296,  287,  287,  287,  287,  287,  283,  288,  289,  283,
      283,  283,  283,  290,  283,  291,  283,  283,  283,  283,

      292,  292,  292,  292,  292,  293,  283,  283,  283,  294,
      283,  294,  294,  294,  297,  298,  283,  294,  283,  295,
      283,  283,  283,  283,  283,  296,  283,  287,  287,  283,
      283,  283,  283,  292,  292,  292,  292,  283,  283,  294,
      294,  283,  297,  283,  298,  145,  299,  283,  283,  287,
      287,  287,  287,  283,  283,  283,  283,  283,  292,  292,
      292,  292,  283,  283,  294,  294,  299,  299,  283,  283,
      287,  287,  287,  283,  283,  283,  283,  292,  292,  292,
      292,  283,  300,  294,  294,  283,  300,  287,  287,  287,
      283,  292,  283,  292,  292,  283,  283,  187,  187,  301,

      187,  294,  294,  287,  287,  287,  283,  292,  283,  292,
      292,  283,  301,  301,  283,  294,  294,  287,  287,  287,
      283,  292,  283,  283,  292,  283,  283,  283,  294,  294,
      287,  287,  287,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  287,  287,  283,  283,  283,  283,  283,  283,
      283,  287,  283,  283,  283,  283,  283,  287,  283,  283,
      283,  283,  287,  283,  283,  283,  283,  287,  283,  283,
      283,  283,  283,  287,  283,  283,  283,  287,  283,  283,
      287,  287,    0,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,

      283
    } ;

static const flex_int16_t yy_nxt[895] =
    {   0,
      283,   49,   50,   49,   50,  109,  280,  109,   79,   51,
      279,   51,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   83,   83,   83,  114,  280,   99,  165,   90,   84,
       84,   85,  100,   91,   52,   92,   52,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   53,   53,   53,   50,   50,   50,   50,
       50,   50,   50,   50,   83,   50,   50,   50,   50,   93,
       99,  109,   84,  111,  119,  279,  100,  117,   95,   99,

      112,   86,   99,  121,  118,  100,  107,  105,  100,  109,
      174,  216,   50,   50,   57,   50,   50,   50,   50,   50,
       50,   50,   50,  102,   50,   50,   50,   50,  104,  122,
      108,  124,  109,  113,   83,   83,   83,  125,  123,   83,
      127,   90,   84,   84,   85,  175,   91,   85,   92,  128,
      202,   50,   50,   57,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       50,   50,   50,   60,   99,   99,  157,  275,  277,  158,

      100,  100,  276,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   50,   62,   50,   50,   50,   63,   50,   50,   64,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   65,
       64,   64,   64,   66,   64,   67,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   68,   64,   50,   50,   50,
       50,   70,   50,   71,   50,   63,   50,   50,   71,   50,
       50,   50,   50,   72,   72,   72,   72,   50,   73,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   74,   71,   50,   50,   50,   75,

       75,   75,  109,   99,  157,   93,   93,  158,   75,  100,
       76,   76,   76,   83,   95,   95,   71,   71,   71,   76,
      111,   84,   99,   99,   99,   71,  103,  112,  100,  100,
      100,  141,   71,   71,   71,   77,   77,   77,  109,  275,
       99,   71,  129,  119,   77,   75,  100,  136,  117,  135,
      134,  109,  121,  109,  119,  118,   76,   78,   78,   78,
       78,  122,   71,  121,  269,  124,  140,  124,  184,  137,
      123,  125,  144,  125,  127,  267,  127,  217,   71,  168,
      266,   77,   50,   50,   50,   50,   50,   80,   50,   50,
       81,   50,   50,   50,   50,   50,   50,   50,   50,   50,

       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   50,   50,
       50,  144,   83,  150,  262,  109,   99,  109,  146,  261,
       84,   84,  100,  147,  147,  147,  147,  151,  152,  174,
       99,   99,  185,   99,  150,  153,  100,  100,  159,  100,
      166,  260,   84,   83,   83,   83,  254,  160,  151,  152,
       83,   84,   84,   84,   99,   99,  162,  109,   84,   99,
      100,  100,  161,  144,  175,  100,  171,  173,  204,  259,
      146,  178,  181,  172,   99,  147,  147,  147,  147,  144,
      100,   83,   83,  179,  251,  257,  168,   83,  229,   84,

       84,  147,  147,  147,  147,   84,   99,  180,   99,  189,
       99,  109,  100,   99,  100,  190,  100,  188,  256,  100,
      255,  254,   99,  253,  192,  194,  193,   83,  100,  203,
       83,  195,  197,   83,   99,   84,  249,   99,   84,  199,
      100,   84,  208,  100,  200,  200,  200,  200,   83,  248,
      109,  206,  201,  197,   83,  205,   84,   99,  210,  247,
      199,  211,   84,  100,  218,  200,  200,  200,  200,  197,
      230,   99,   99,  219,  220,  246,  214,  100,  100,  197,
      245,  200,  200,  200,  200,   83,  214,  224,  222,   83,
      233,  241,  225,   84,  235,  239,   83,   84,   84,  236,

      100,  100,  236,   83,   84,  231,  232,  233,  243,  242,
      235,   84,  240,  239,  250,   84,  100,  251,  236,  100,
      107,   83,  236,  107,  238,   83,  250,   83,   83,   84,
      264,   83,  244,   84,  236,   84,   84,  264,  265,   84,
      270,  272,   83,  270,  272,  265,   83,  237,  271,  273,
       84,  271,  273,  252,   84,  263,  268,   83,  258,  274,
       83,   83,  234,  228,  227,   84,  226,  223,   84,   84,
      221,  215,  212,  209,  207,  196,  177,  278,  191,  170,
      187,  186,  183,  182,  281,  177,  282,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   53,   53,

       53,   53,   53,   53,   53,   53,   53,   53,   53,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       82,   82,  176,   82,   82,   82,   82,   82,   82,   82,
       82,   88,  170,   88,   88,   88,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   94,  169,  142,  164,
       94,   94,  163,  156,   94,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,  101,  155,  154,  101,  101,
      149,  148,  142,  101,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  110,  139,  110,  109,  110,  107,
      110,  138,  110,  120,  133,  132,  131,  120,  120,  120,

      126,   90,  130,  126,  126,  126,  116,  115,  126,  143,
      107,  143,  109,  143,   98,  143,   97,  143,  145,   87,
      145,  283,  145,   55,  145,   55,  145,  167,   69,  167,
       69,  167,   55,  167,   55,  167,  198,   61,  198,   61,
      198,   58,  198,   58,  198,  213,   55,  213,   55,  213,
      283,  213,  283,  213,   47,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283

    } ;

static const flex_int16_t yy_chk[895] =
    {   0,
        0,    1,    1,    2,    2,  140,  280,   74,   43,    1,
      279,    2,   44,   43,   43,   43,   43,   44,   44,   44,
       44,   48,   49,   51,   74,  277,   64,  140,   59,   48,
       49,   51,   64,   59,    1,   59,    2,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    7,    7,    7,    7,
        7,    7,    7,    7,   52,    7,    7,    7,    7,   60,
       68,  202,   52,   72,   79,  276,   68,   78,   60,   65,

       72,   52,   67,   79,   78,   65,   70,   68,   67,   73,
      154,  202,    7,    7,    7,    8,    8,    8,    8,    8,
        8,    8,    8,   65,    8,    8,    8,    8,   67,   80,
       70,   81,  184,   73,   82,   83,   84,   81,   80,   85,
       81,   92,   82,   83,   84,  154,   92,   85,   92,   85,
      184,    8,    8,    8,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   13,   99,  101,  133,  275,  273,  133,

       99,  101,  271,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   35,

       36,   37,  114,   66,  157,   93,   94,  157,   38,   66,
       35,   36,   37,   86,   93,   94,   35,   36,   37,   38,
      112,   86,  102,  103,  104,   38,   66,  112,  102,  103,
      104,  114,   35,   36,   37,   35,   36,   37,  113,  269,
      105,   38,   86,  119,   38,   39,  105,  104,  118,  103,
      102,  165,  119,  203,  120,  118,   39,   39,   39,   39,
       39,  122,   39,  120,  265,  124,  113,  126,  165,  105,
      122,  124,  168,  126,  124,  262,  126,  203,   39,  168,
      261,   39,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,  116,  129,  128,  257,  166,  134,  141,  116,  256,
      129,  128,  134,  116,  116,  116,  116,  128,  128,  174,
      135,  136,  166,  137,  150,  129,  135,  136,  134,  137,
      141,  255,  150,  151,  152,  188,  254,  135,  150,  150,
      153,  151,  152,  188,  159,  162,  137,  216,  153,  160,
      159,  162,  136,  145,  174,  160,  151,  153,  188,  253,
      145,  159,  162,  152,  161,  145,  145,  145,  145,  147,
      161,  171,  172,  160,  251,  249,  147,  173,  216,  171,

      172,  147,  147,  147,  147,  173,  178,  161,  180,  172,
      179,  185,  178,  181,  180,  173,  179,  171,  248,  181,
      247,  246,  192,  245,  178,  180,  179,  190,  192,  185,
      189,  181,  183,  204,  194,  190,  240,  195,  189,  183,
      194,  204,  192,  195,  183,  183,  183,  183,  205,  238,
      217,  190,  183,  187,  206,  189,  205,  208,  194,  237,
      187,  195,  206,  208,  204,  187,  187,  187,  187,  200,
      217,  210,  211,  205,  206,  236,  200,  210,  211,  214,
      234,  200,  200,  200,  200,  218,  214,  210,  208,  219,
      220,  229,  211,  218,  222,  225,  231,  219,  220,  229,

      222,  225,  222,  232,  231,  218,  219,  233,  231,  230,
      235,  232,  226,  239,  241,  233,  235,  242,  235,  239,
      241,  243,  241,  242,  224,  244,  250,  252,  258,  243,
      260,  263,  232,  244,  250,  252,  258,  264,  260,  263,
      266,  267,  268,  270,  272,  264,  274,  223,  266,  267,
      268,  270,  272,  243,  274,  258,  263,  278,  252,  268,
      281,  282,  221,  215,  213,  278,  212,  209,  281,  282,
      207,  201,  196,  193,  191,  182,  177,  274,  176,  170,
      169,  167,  164,  163,  278,  158,  281,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  285,  285,

      285,  285,  285,  285,  285,  285,  285,  285,  285,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      287,  287,  155,  287,  287,  287,  287,  287,  287,  287,
      287,  288,  149,  288,  288,  288,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  290,  148,  143,  139,
      290,  290,  138,  132,  290,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  292,  131,  130,  292,  292,
      125,  117,  115,  292,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  294,  111,  294,  110,  294,  109,
      294,  108,  294,  295,  100,   98,   97,  295,  295,  295,

      296,   90,   87,  296,  296,  296,   77,   76,  296,  297,
       75,  297,   71,  297,   63,  297,   62,  297,  298,   55,
      298,   47,  298,   32,  298,   31,  298,  299,   26,  299,
       25,  299,   22,  299,   21,  299,  300,   16,  300,   15,
      300,   10,  300,    9,  300,  301,    6,  301,    5,  301,
        0,  301,    0,  301,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tema.l"
#line 2 "tema.l"
    /* MANEA STEFANIA-DELIA 335CC*/
#include <stdio.h>
#include <stdlib.h>
#include <regex.h>
#include <stdbool.h>

typedef struct {
    char state[100];
    char symbol;
    char next_state[100];
} Tranzitie;

typedef struct {
    int type;
    int num_states;
    char initial_state[100];
    char final_states[100];
    char alphabet[100];
    bool active_variable;
    char identificator[100];
    char domeniu[100];
    int num_transitions;
    Tranzitie tranzitii[100];
} Automat;

typedef struct {
    int type;
    int num_reguli;
    char alphabet[100];
    int alphabet_size;
    char start_symbol[100];
    bool active_variable;
    char identificator[100];
    char domeniu[100];
    int l;
} Gramatica;

typedef struct {
    char identificator[100];
    char domeniu[100];
} VariabilaGlobala;

Automat a[100];
int n = 0;  // numarul de automate
Gramatica g[100];
int m = 0;  // numarul de gramatici
VariabilaGlobala v[100];
int k = 0;  // numarul de variabile globale

char prev_state[100];
int prev_pos;

// returneaza tipul gramaticii
char *get_tip_gramatica(int type) {
    switch (type) {
        case 0:
            return "GFR";
        case 1:
            return "GDC";
        case 2:
            return "GIC";
        case 3:
            return "GR";
    }
}

void print_automat() {
    // tipul automatului
    if (a[n].type == 0) {
        printf("Tipul automatului: Automat finit nedeterminist\n");
    } else {
        printf("Tipul automatului: Automat finit determinist\n");
    }

    // alfabetul
    printf("Alfabetul de intrare: {");
    printf("%s", a[n].alphabet);
    printf("}\n");
    
    // stari
    printf("Numarul de stari: %d\n", a[n].num_states);
    // stare initiala
    printf("Starea initiala: %s\n", a[n].initial_state);
    // stari finale
    printf("Stari finale: {");
    printf("%s", a[n].final_states);
    printf("}\n");

    // tranzitii
    printf("Functia de tranzitie:\n");
    for(int i = 0; i < a[n].num_transitions; i++) {
        printf("\tm(%s, %c) = %s\n", a[n].tranzitii[i].state, a[n].tranzitii[i].symbol, a[n].tranzitii[i].next_state);
    }

    // variabila locala
    if (a[n].active_variable) {
        printf("Variabila locala:\n");
        printf("\tIdentificator: %s\n", a[n].identificator);
        printf("\tDomeniu: {");
        for (int i = 0; i < strlen(a[n].domeniu); i++) {
            if (i == strlen(a[n].domeniu) - 1) {
                printf("%c}\n", a[n].domeniu[i]);
            } else {
                printf("%c, ", a[n].domeniu[i]);
            }
        }
    }
}

void print_gramatica() {
    // tipul gramaticii
    printf("Tipul gramaticii: %s\n", get_tip_gramatica(g[m].type));

    // numarul de reguli de productie
    printf("Numarul de reguli de productie: %d\n", g[m].num_reguli);

    // alfabetul
    printf("Alfabetul de intrare: {");
    printf("%s", g[m].alphabet);
    printf("}\n");

    // variabila locala
    if (g[m].active_variable) {
        printf("Variabila locala:\n");
        printf("\tIdentificator: %s\n", g[m].identificator);
        printf("\tDomeniu: {");
        for (int i = 0; i < strlen(g[m].domeniu); i++) {
            if (i == strlen(g[m].domeniu) - 1) {
                printf("%c}\n", g[m].domeniu[i]);
            } else {
                printf("%c, ", g[m].domeniu[i]);
            }
        }
    }
}

int current_file_index = 0;
char *file_list[100]; // lista fisierelor de intrare
int total_files = 0;  // numarul total de fisiere

int yywrap(void) {
    if (current_file_index < total_files - 1) {
        current_file_index++;
        yyin = fopen(file_list[current_file_index], "r");
        if (!yyin) {
            perror("Nu s-a putut deschide fisierul\n");
            return 1;
        }
        printf("\n      =================Am deschis fisierul %s====================\n", file_list[current_file_index]);
        return 0; // continua cu urmatorul fisier
    }
    return 1; // am terminat de procesat fisierele
}

#line 891 "lex.yy.c"

#line 893 "lex.yy.c"

#define INITIAL 0
#define IDENTIFICATOR 1
#define IGNORE 2
#define DOMENIU 3
#define ALPHABET 4
#define STATES 5
#define INITIAL_STATE 6
#define FINAL_STATE 7
#define AUTOMAT 8
#define IDENTIFICATOR_A 9
#define IGNORE_A 10
#define DOMENIU_A 11
#define ALPHABET_G 12
#define GRAMATICA 13
#define IDENTIFICATOR_G 14
#define IGNORE_G 15
#define DOMENIU_G 16
#define GR 17
#define GIC 18
#define GDC 19
#define GFR 20
#define START_SYMBOL 21
#define TRANSITIONS 22

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 160 "tema.l"


#line 163 "tema.l"
    /* identificarea variabilelor */
#line 1137 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 284 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 855 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 164 "tema.l"
{
    if (YY_START == INITIAL) {
        printf("Variabilă globală:\n");
        BEGIN(IDENTIFICATOR);
    } else {
        if (YY_START == AUTOMAT) {           
            BEGIN(IDENTIFICATOR_A);
        } else {
            BEGIN(IDENTIFICATOR_G);
        }
    }
}
	YY_BREAK
/* identificatorul variabilei */
case 2:
YY_RULE_SETUP
#line 178 "tema.l"
{
    if (YY_START == IDENTIFICATOR) {
        printf("\tIdentificator:  %s\n", yytext);
        strcpy(v[k].identificator, yytext);    
        BEGIN(IGNORE);
    } else {
        if (YY_START == IDENTIFICATOR_A) {
            a[n].active_variable = true;
            strcpy(a[n].identificator, yytext);
            BEGIN(IGNORE_A);
        } else {
            g[m].active_variable = true;
            strcpy(g[m].identificator, yytext);
            BEGIN(IGNORE_G);
        }
    }
}
	YY_BREAK
/* pentru varibile ignor niste caractere */
case 3:
YY_RULE_SETUP
#line 197 "tema.l"
{
    if (YY_START == IGNORE) {
        BEGIN(DOMENIU);
    } else {
        if (YY_START == IGNORE_A) {
            BEGIN(DOMENIU_A);
        } else {
            BEGIN(DOMENIU_G);
        }
    }
}
	YY_BREAK
/* construiesc domeniul variabilei */
case 4:
YY_RULE_SETUP
#line 210 "tema.l"
{
    if (YY_START == DOMENIU) {
        strncat(v[k].domeniu, yytext, sizeof(v[k].domeniu) - strlen(v[k].domeniu) - 1);
    } else if (YY_START == DOMENIU_A) {
        strncat(a[n].domeniu, yytext, sizeof(a[n].domeniu) - strlen(a[n].domeniu) - 1);
    } else {
        strncat(g[m].domeniu, yytext, sizeof(g[m].domeniu) - strlen(g[m].domeniu) - 1);
    }
}
	YY_BREAK
/* termin de construit domeniul variabilei */
case 5:
YY_RULE_SETUP
#line 221 "tema.l"
{
    if (YY_START == DOMENIU) {
        printf("\tDomeniu: {");
        for (int i = 0; i < strlen(v[k].domeniu); i++) {
            if (i == strlen(v[k].domeniu) - 1) {
                printf("%c}\n", v[k].domeniu[i]);
            } else {
                printf("%c, ", v[k].domeniu[i]);
            }
        }
        k++;
        BEGIN(INITIAL);
    } else if (YY_START == DOMENIU_A) {
        BEGIN(AUTOMAT);
    } else {
        BEGIN(GRAMATICA);
    }
}
	YY_BREAK
/* identific automat si printez numele lui */
case 6:
YY_RULE_SETUP
#line 241 "tema.l"
{ 
    printf("\n");
    yyless(yyleng - 20);
    printf("Numele automatului: %s\n", yytext);
    a[n].type = 1;
    a[n].active_variable = false;
    a[n].num_transitions = 0;
    BEGIN(AUTOMAT);
}
	YY_BREAK
/* identific gramatic si printez numele lui */
case 7:
YY_RULE_SETUP
#line 252 "tema.l"
{ 
    printf("\n");
    yyless(yyleng - 12);
    printf("Numele gramaticii: %s\n", yytext);
    g[m].num_reguli = 0;
    g[m].active_variable = false;
    g[m].l = 0;
    BEGIN(GRAMATICA);
}
	YY_BREAK
/* identific alfabetul */
case 8:
YY_RULE_SETUP
#line 263 "tema.l"
{
    if (YY_START == AUTOMAT) {
        BEGIN(ALPHABET);
    } else {
        BEGIN(ALPHABET_G);
    }
}
	YY_BREAK
/* retin alfabetul automatului */
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 272 "tema.l"
{
    yyless(yyleng - 1); // ca sa sterg spatiul de dupa ultimul caracter din domeniu
    strcpy(a[n].alphabet, yytext + 2);
    BEGIN(AUTOMAT); 
}
	YY_BREAK
/* retin alfabetul gramaticii */
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 279 "tema.l"
{
    yyless(yyleng - 1); // ca sa sterg spatiul de dupa ultimul caracter din domeniu
    strcpy(g[m].alphabet, yytext + 2);
    BEGIN(GRAMATICA); 
}
	YY_BREAK
/* identific inceputul starilor initiale */
case 11:
YY_RULE_SETUP
#line 286 "tema.l"
{
    BEGIN(INITIAL_STATE);
}
	YY_BREAK
/* identific starile initiale si le retin */
case 12:
YY_RULE_SETUP
#line 291 "tema.l"
{
    strncpy(a[n].initial_state, yytext, yyleng - 1);
    BEGIN(AUTOMAT);
}
	YY_BREAK
/* identific inceputul starilor finale */
case 13:
YY_RULE_SETUP
#line 297 "tema.l"
{
    BEGIN(FINAL_STATE);
}
	YY_BREAK
/* identific starile finale si le retin */
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 302 "tema.l"
{
    yyless(yyleng - 1); // ca sa sterg spatiul de dupa ultimul caracter din domeniu
    strcpy(a[n].final_states, yytext + 2);
    BEGIN(AUTOMAT); 
}
	YY_BREAK
/* identific inceputul starilor */
case 15:
YY_RULE_SETUP
#line 309 "tema.l"
{
    a[n].num_states = 0;
    BEGIN(STATES);
}
	YY_BREAK
/* identific starile si le retin */
case 16:
YY_RULE_SETUP
#line 315 "tema.l"
{
        a[n].num_states++;
}
	YY_BREAK
/* identific ultima stare si o retin */
case 17:
YY_RULE_SETUP
#line 320 "tema.l"
{
    a[n].num_states++;
    BEGIN(AUTOMAT);
}
	YY_BREAK
/* identific starea de plecare */
case 18:
YY_RULE_SETUP
#line 326 "tema.l"
{
    yyless(yyleng - 5);
    strcpy(prev_state, yytext);
    prev_pos = a[n].num_transitions;
    BEGIN(TRANSITIONS);
}
	YY_BREAK
/* identific simbolul cu care se face tranzitia*/
case 19:
YY_RULE_SETUP
#line 334 "tema.l"
{
    strcpy(a[n].tranzitii[a[n].num_transitions].state, prev_state);
    a[n].tranzitii[a[n].num_transitions].symbol = yytext[0];
    // daca simbolul este 'e', automatul este nedeterminist
    if (yytext[0] == 'e') {
        a[n].type = 0;
    }
}
	YY_BREAK
/* identific starea in care se ajunge */
case 20:
YY_RULE_SETUP
#line 344 "tema.l"
{
    yyless(yyleng - 2);
    char t = a[n].tranzitii[a[n].num_transitions].symbol;
    int ok = 0;

    // verific dacă simbolul este o variabila globala
    for (int i = 0; i < k; i++) {
        if (t == v[i].identificator[0]) {
            for (int j = 0; j < strlen(v[i].domeniu); j++) {
                // adaug tranzitia pentru fiecare simbol din domeniu               
                strcpy(a[n].tranzitii[a[n].num_transitions].state, prev_state);
                a[n].tranzitii[a[n].num_transitions].symbol = v[i].domeniu[j];
                strcpy(a[n].tranzitii[a[n].num_transitions].next_state, yytext);
                a[n].num_transitions++;
            }
            ok = 1;
        }
    }

    // verific daca simbolul este o variabila locala
    if (a[n].active_variable && t == a[n].identificator[0]) {
        for (int i = 0; i < strlen(a[n].domeniu); i++) {
            // adaug tranzitia pentru fiecare simbol din domeniu
            strcpy(a[n].tranzitii[a[n].num_transitions].state, prev_state);
            a[n].tranzitii[a[n].num_transitions].symbol = a[n].domeniu[i];
            strcpy(a[n].tranzitii[a[n].num_transitions].next_state, yytext);
            a[n].num_transitions++;
        }
        ok = 1;
    }

    // daca nu este o variabila, trateaz simbolul normal
    if (ok == 0) {
        strcpy(a[n].tranzitii[a[n].num_transitions].state, prev_state);
        a[n].tranzitii[a[n].num_transitions].symbol = t;
        strcpy(a[n].tranzitii[a[n].num_transitions].next_state, yytext);
        a[n].num_transitions++;
    }
}
	YY_BREAK
/* identific sfarsitul tranzitiei */
case 21:
YY_RULE_SETUP
#line 385 "tema.l"
{
    for (int i = prev_pos; i < a[n].num_transitions - 1; i++) {
        for (int j = i + 1; j < a[n].num_transitions; j++) {
            if (a[n].tranzitii[i].symbol == a[n].tranzitii[j].symbol) {
                a[n].type = 0;
                break;
            }
        }
    }
    BEGIN(AUTOMAT);
}
	YY_BREAK
/* identific inceputul simbolului de start */
case 22:
YY_RULE_SETUP
#line 398 "tema.l"
{
    BEGIN(START_SYMBOL);
}
	YY_BREAK
/* identific simbolul de start si il retin */
case 23:
YY_RULE_SETUP
#line 403 "tema.l"
{
    strncpy(g[m].start_symbol, yytext, yyleng - 2);
    BEGIN(GRAMATICA);
}
	YY_BREAK
/* identific inceputul regulii de productie */
case 24:
YY_RULE_SETUP
#line 409 "tema.l"
{
    
    yyless(yyleng - 7);
    // daca simbolul de start merge doar in 'e', gramatica e dependenta de context
    if (strcmp(yytext, g[m].start_symbol) == 0) {
        g[m].type = 1;
        BEGIN(GDC);
    } else {
        g[m].num_reguli++;
    }
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 421 "tema.l"
{ // pt GR
    g[m].num_reguli++;
    g[m].l = 0;
    if (YY_START == GRAMATICA) {
        g[m].type = 3;
        BEGIN(GR);
    }
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 430 "tema.l"
{ // pt GR
    g[m].num_reguli++;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 434 "tema.l"
{ // pt GIC
    g[m].num_reguli++;
    g[m].l = 0;
    // daca sunt la inceputul gramaticii sau pana acum am avut doar reguli de tip 3 trec la tip 2
    if (YY_START == GRAMATICA || YY_START == GR) {
        g[m].type = 2;
        BEGIN(GIC);
    }
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 444 "tema.l"
{  // pt GFR 
    g[m].num_reguli++;
    if (g[m].l != 0 && g[m].l > yyleng - 3) {
        g[m].type = 0;
        BEGIN(GFR);
    }
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 452 "tema.l"
{  // pt GDC
    g[m].l = yyleng - 2;
    g[m].type = 1;
    BEGIN(GDC);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 458 "tema.l"
{  // pt GFR
    g[m].num_reguli++;
    if (g[m].l > yyleng - 3) {
        g[m].type = 0;
        BEGIN(GFR);
    }
}
	YY_BREAK
/* identific sfarsitul definitiei automatului/gramaticii */
case 31:
YY_RULE_SETUP
#line 467 "tema.l"
{
    if (YY_START == AUTOMAT) {
        print_automat();
        n++;
    } else {
        print_gramatica();
        m++;
    }
    BEGIN(INITIAL);
}
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 478 "tema.l"
{ /* ignor alte caractere */ }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 481 "tema.l"
ECHO;
	YY_BREAK
#line 1615 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IDENTIFICATOR):
case YY_STATE_EOF(IGNORE):
case YY_STATE_EOF(DOMENIU):
case YY_STATE_EOF(ALPHABET):
case YY_STATE_EOF(STATES):
case YY_STATE_EOF(INITIAL_STATE):
case YY_STATE_EOF(FINAL_STATE):
case YY_STATE_EOF(AUTOMAT):
case YY_STATE_EOF(IDENTIFICATOR_A):
case YY_STATE_EOF(IGNORE_A):
case YY_STATE_EOF(DOMENIU_A):
case YY_STATE_EOF(ALPHABET_G):
case YY_STATE_EOF(GRAMATICA):
case YY_STATE_EOF(IDENTIFICATOR_G):
case YY_STATE_EOF(IGNORE_G):
case YY_STATE_EOF(DOMENIU_G):
case YY_STATE_EOF(GR):
case YY_STATE_EOF(GIC):
case YY_STATE_EOF(GDC):
case YY_STATE_EOF(GFR):
case YY_STATE_EOF(START_SYMBOL):
case YY_STATE_EOF(TRANSITIONS):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 284 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 284 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 283);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 481 "tema.l"


int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s\n", argv[0]);
        return 1;
    }

    // initializeaza lista de fisiere
    for (int i = 1; i < argc; i++) {
        file_list[total_files++] = argv[i];
    }

    // deschide primul fisier
    yyin = fopen(file_list[current_file_index], "r");
    if (!yyin) {
        perror("Nu s-a putut deschide fisierul\n");
        return 1;
    }
    printf("        =================Am deschis fisierul %s====================\n", file_list[current_file_index]);
    yylex();

    return 0;
}


